// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/3/2026, 3:27:25 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Yonier Ospina/first-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","components/atoms/**/*.{vue,js,jsx,mjs,ts,tsx}","components/molecules/**/*.{vue,js,jsx,mjs,ts,tsx}","components/organisms/**/*.{vue,js,jsx,mjs,ts,tsx}","components/templates/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Yonier Ospina/first-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Yonier Ospina/first-project/plugins/**/*.{js,ts,mjs}","C:/Users/Yonier Ospina/first-project/composables/**/*.{js,ts,mjs}","C:/Users/Yonier Ospina/first-project/utils/**/*.{js,ts,mjs}","C:/Users/Yonier Ospina/first-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Yonier Ospina/first-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Yonier Ospina/first-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Yonier Ospina/first-project/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;